{
 "title": "VAUED - Kafka Dashboard",
 "description": "Kafka resource usage and throughput",
 "time": { "from": "now-30m", "to": "now" },
 "panels": [
  {
   "title": "CPU Usage",
   "type": "gauge",
   "gridPos": { "h": 7, "w": 5, "x": 0, "y": 0 },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "rate(process_cpu_seconds_total{job=\"kafka\"}[5m])",
     "legendFormat": "{{instance}}"
    }
   ]
  },
  {
   "title": "JVM Memory Used",
   "type": "gauge",
   "gridPos": { "h": 7, "w": 6, "x": 5, "y": 0 },
   "fieldConfig": { "defaults": { "unit": "bytes" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "sum without(area)(jvm_memory_bytes_used{job=\"kafka\"})",
     "legendFormat": "{{instance}}"
    }
   ]
  },
  {
   "type": "text",
   "gridPos": { "h": 7, "w": 1, "x": 11, "y": 0 },
   "options": {
    "content": "---\n\n # K\n\n # A\n\n # F\n\n # K\n\n # A\n\n ---        "
   }
  },
  {
   "title": "Prometheus Scrape Duration",
   "type": "graph",
   "gridPos": { "h": 7, "w": 6, "x": 12, "y": 0 },
   "yaxes": [
    { "format": "short" }
   ],
   "targets": [
    { "expr": "scrape_duration_seconds" }
   ]
  },
  {
   "title": "JMX Exporter Scrape Duration",
   "type": "graph",
   "gridPos": { "h": 7, "w": 6, "x": 18, "y": 0 },
   "yaxes": [
    { "format": "short" }
   ],
   "targets": [
    { "expr": "jmx_scrape_duration_seconds" }
   ]
  },
  {
   "title": "Partition Count",
   "type": "stat",
   "gridPos": { "h": 3, "w": 6, "x": 0, "y": 7 },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "kafka_controller_kafkacontroller_globalpartitioncount"
    }
   ]
  },
  {
   "title": "Active Controller Count",
   "type": "stat",
   "description": "One of the brokers is an active controller and all the ones are not controllers. This number should always be one.\nZero means Kafka cluster is not working.",
   "gridPos": { "h": 3, "w": 3, "x": 6, "y": 7 },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "kafka_controller_kafkacontroller_activecontrollercount"
    }
   ]
  },
  {
   "title": "Kafka topic count",
   "type": "stat",
   "gridPos": { "h": 3, "w": 3, "x": 9, "y": 7 },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "kafka_controller_kafkacontroller_globaltopiccount"
    }
   ]
  },
  {
   "title": "Total Message Count ",
   "type": "stat",
   "description": "Total message count of all topics",
   "gridPos": { "h": 3, "w": 4, "x": 12, "y": 7 },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "kafka_server_brokertopicmetrics_messagesin_total"
    }
   ]
  },
  {
   "title": "Total Consumer Requests",
   "type": "stat",
   "gridPos": { "h": 3, "w": 4, "x": 16, "y": 7 },
   "fieldConfig": { "defaults": { "unit": "short" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "sum(kafka_server_brokertopicmetrics_totalfetchrequests_total)"
    }
   ]
  },
  {
   "title": "Total Producer Requests",
   "type": "stat",
   "gridPos": { "h": 3, "w": 4, "x": 20, "y": 7 },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "sum(kafka_server_brokertopicmetrics_totalproducerequests_total)\r"
    }
   ]
  },
  {
   "title": "Offline Partitions",
   "type": "stat",
   "description": "This is the number of partitions that are offline in the cluster. This number should always be zero. If a partition is offline (down), means that the topics are also down).",
   "gridPos": { "h": 3, "w": 3, "x": 0, "y": 10 },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "kafka_controller_kafkacontroller_offlinepartitionscount"
    }
   ]
  },
  {
   "title": "URP",
   "type": "stat",
   "description": "Under Replicated Partitions. Should always be zero.\n\n",
   "gridPos": { "h": 3, "w": 3, "x": 3, "y": 10 },
   "fieldConfig": { "defaults": { "unit": "short" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "kafka_server_replicamanager_underreplicatedpartitions"
    }
   ]
  },
  {
   "title": "Messages In Per Topic",
   "type": "graph",
   "gridPos": { "h": 8, "w": 6, "x": 6, "y": 10 },
   "yaxes": [
    { "format": "short", "label": "Messages/s" }
   ],
   "targets": [
    {
     "expr": "sum without(instance)(rate(kafka_server_brokertopicmetrics_messagesin_total{job=\"kafka\",topic!=\"\"}[60m]))",
     "legendFormat": "{{topic}}"
    }
   ]
  },
  {
   "title": "Bytes In Per Topic",
   "type": "graph",
   "gridPos": { "h": 8, "w": 6, "x": 12, "y": 10 },
   "yaxes": [
    { "format": "Bps", "label": "Bytes/s" }
   ],
   "targets": [
    {
     "expr": "sum without(instance)(rate(kafka_server_brokertopicmetrics_bytesin_total{job=\"kafka\",topic!=\"\"}[60m]))",
     "legendFormat": "{{topic}}"
    }
   ]
  },
  {
   "title": "Bytes Out Per Topic",
   "type": "graph",
   "gridPos": { "h": 8, "w": 6, "x": 18, "y": 10 },
   "yaxes": [
    { "format": "Bps", "label": "Bytes/s" }
   ],
   "targets": [
    {
     "expr": "sum without(instance)(rate(kafka_server_brokertopicmetrics_bytesout_total{job=\"kafka\",topic!=\"\"}[60m]))",
     "legendFormat": "{{topic}}"
    }
   ]
  },
  {
   "title": "Time spent in GC",
   "type": "graph",
   "gridPos": { "h": 5, "w": 6, "x": 0, "y": 13 },
   "yaxes": [
    { "format": "percentunit", "label": "% time in GC" }
   ],
   "targets": [
    {
     "expr": "sum without(gc)(rate(jvm_gc_collection_seconds_sum{job=\"kafka\"}[5m]))",
     "legendFormat": "{{instance}}"
    }
   ]
  }
 ]
}